server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/auth/**
          - id: tracker-service
            uri: lb://tracker-service
            predicates:
              - Path=/applications/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
